# Workflow Configuration Schema
# Multi-Agent Framework - Contract Definition
#
# This schema defines how to configure multi-agent workflows with composable patterns.
# Workflows define the execution flow as a graph of nodes and edges.

# Workflow definition (工作流定义)
workflow:
  type: object
  required:
    - name
    - entry_point
    - nodes
    - edges
  properties:
    name:
      type: string
      description: Unique workflow identifier (唯一的工作流标识符)
      example: "research_pipeline"

    description:
      type: string
      description: Human-readable workflow description (工作流的描述说明)
      example: "Researches a topic and writes a summary"

    patterns:
      type: array
      items:
        type: string
        enum: [react, reflection, cot, debate, tot]
      description: |
        Composable pattern sequence
        (可组合的模式序列，定义代理的推理方式)
        - react: ReAct 模式 (Reason → Act → Observe 循环)
        - reflection: 反思模式 (生成 → 批评 → 改进)
        - cot: 思维链模式 (Chain-of-Thought，逐步推理)
        - debate: 辩论模式 (多代理相互辩论)
        - tot: 思维树模式 (Tree of Thoughts，探索多条路径)
      example: ["react", "reflection"]

    entry_point:
      type: string
      description: Starting node name (起始节点名称)
      example: "supervisor"

    nodes:
      type: object
      # pattern: 正则表达式模式，用于节点名称的格式验证
      # ^[a-z][a-z0-9_]*$ 表示：以小写字母开头，后面可以是小写字母、数字或下划线
      patternProperties:
        "^[a-z][a-z0-9_]*$":
          type: object
          required:
            - type
          properties:
            # type: 节点类型，定义节点的行为
            type:
              type: string
              enum: [agent, tool, condition, human, parallel]
              description: |
                Node type defining behavior
                - agent: 代理节点，由 AI 代理处理
                - tool: 工具节点，直接调用工具
                - condition: 条件节点，根据状态进行路由
                - human: 人工节点，暂停等待人类输入
                - parallel: 并行节点，并行执行多个子任务
              example: "agent"

            agent:
              type: string
              description: Agent name (for type=agent nodes)
              example: "researcher"

            tool:
              type: string
              description: Tool name (for type=tool nodes)
              example: "web_search"

            condition:
              type: string
              description: |
                Expression to evaluate (for type=condition nodes)
                条件表达式，返回目标节点名称
              example: "state['has_data'] == 'yes'"

            parallel_tasks:
              type: array
              items:
                type: string
              description: |
                List of node names to execute in parallel (for type=parallel)
                要并行执行的节点名称列表
              example: ["task_a", "task_b"]

            allow_human_input:
              type: boolean
              default: false
              description: |
                Enable human-in-the-loop at this node
                是否在此节点启用人工干预
                - true: 执行到此节点时暂停，等待人类审批
                - false: 自动执行不暂停

            max_iterations:
              type: integer
              minimum: 1
              default: 10
              description: |
                Maximum iterations for this node
                此节点的最大执行迭代次数
              example: 5

    edges:
      type: array
      items:
        type: object
        required:
          - from
          - to
        properties:
          from:
            type: string
            description: Source node name (源节点名称)
            example: "supervisor"

          to:
            oneOf:
              - type: string
                description: Target node name (目标节点名称)
                example: "researcher"
              - type: object
                description: |
                  Conditional routing (条件路由映射)
                  根据条件值路由到不同节点
                additionalProperties:
                  type: string
                example:
                  approve: "writer"
                  reject: "end"
                  retry: "supervisor"

          condition:
            type: string
            description: |
              Optional condition expression (可选的条件表达式)
              只有条件为真时才会走这条边
            example: "state['quality'] >= 0.8"

    max_iterations:
      type: integer
      minimum: 1
      maximum: 1000
      default: 50
      description: |
        Global workflow iteration limit
        全局工作流迭代次数限制，防止无限循环

    checkpoints:
      type: array
      items:
        type: string
      description: |
        Nodes that support checkpoint/resume
        支持检查点和恢复的节点名称列表
        在这些节点执行后会保存状态快照
      example: ["supervisor", "writer"]

# Example workflow configurations (示例配置)
examples:
  # 简单的单代理工作流
  simple_agent:
    name: simple_agent
    description: "Simple single-agent workflow with ReAct pattern"
    patterns: [react]
    entry_point: agent
    nodes:
      agent:
        type: agent
        agent: web_researcher
        max_iterations: 10
    edges:
      - from: agent
        to: __end__

  # Supervisor 模式：协调多个子代理
  supervisor_workflow:
    name: supervisor_workflow
    description: "Supervisor coordinates research and writing agents"
    patterns: [react]
    entry_point: supervisor
    nodes:
      supervisor:
        type: agent
        agent: supervisor
        allow_human_input: true
      researcher:
        type: agent
        agent: web_researcher
        max_iterations: 5
      writer:
        type: agent
        agent: content_writer
        max_iterations: 5
    edges:
      - from: supervisor
        to:
          delegate_research: researcher
          delegate_write: writer
          complete: __end__
      - from: researcher
        to: supervisor
      - from: writer
        to: supervisor
    checkpoints: [supervisor]

  # Reflection 模式：生成后反思改进
  reflection_workflow:
    name: reflection_workflow
    description: "Generate content, then reflect and improve"
    patterns: [react, reflection]
    entry_point: generator
    nodes:
      generator:
        type: agent
        agent: content_generator
        max_iterations: 5
      reflector:
        type: agent
        agent: content_reflector
        max_iterations: 3
      improver:
        type: agent
        agent: content_improver
        max_iterations: 5
    edges:
      - from: generator
        to: reflector
      - from: reflector
        to:
          needs_improvement: improver
          acceptable: __end__
      - from: improver
        to: reflector

  # 并行执行模式
  parallel_workflow:
    name: parallel_research
    description: "Execute multiple research tasks in parallel"
    patterns: [react]
    entry_point: dispatcher
    nodes:
      dispatcher:
        type: agent
        agent: task_dispatcher
      parallel_tasks:
        type: parallel
        parallel_tasks: [researcher_a, researcher_b, researcher_c]
      aggregator:
        type: agent
        agent: result_aggregator
    edges:
      - from: dispatcher
        to: parallel_tasks
      - from: parallel_tasks
        to: aggregator
      - from: aggregator
        to: __end__

# Pattern descriptions (模式详细说明)
patterns_detail:
  react:
    name: "ReAct Pattern"
    description: |
      Reason → Act → Observe 循环模式
      代理先思考（Reason），然后执行动作（Act），最后观察结果（Observe）
      适合需要多步推理和工具调用的任务
    steps:
      - Thought: 思考当前状态和下一步行动
      - Action: 选择并执行一个工具
      - Observation: 观察工具执行结果
      - 重复直到完成任务

  reflection:
    name: "Reflection Pattern"
    description: |
      反思模式：生成 → 批评 → 改进
      代理生成初始答案，然后批评自己的答案，最后根据批评改进答案
      适合需要高质量输出的任务，如写作、代码生成
    steps:
      - Generate: 生成初始答案
      - Critique: 批评答案的不足之处
      - Refine: 根据批评改进答案
      - 可选：重复批评和改进多次

  cot:
    name: "Chain-of-Thought Pattern"
    description: |
      思维链模式
      代理在给出答案之前，逐步展示推理过程
      适合复杂推理任务，如数学问题、逻辑推理

  debate:
    name: "Debate Pattern"
    description: |
      辩论模式
      多个代理从不同角度讨论同一问题，最后综合得出结论
      适合需要多视角分析的任务，如决策、分析

  tot:
    name: "Tree of Thoughts Pattern"
    description: |
      思维树模式
      代理探索多条可能的推理路径，评估每条路径，选择最优路径
      适合需要探索多种可能性的任务，如创意、规划

# Validation rules (验证规则)
rules:
  - All nodes referenced in edges must exist (所有边引用的节点必须存在)
  - Workflow must be acyclic (no circular dependencies) (工作流必须无循环)
  - Entry point node must exist (起始节点必须存在)
  - __end__ is reserved for termination (保留 __end__ 作为终止节点)
  - Agent names must be defined in agent configurations (代理名称必须在代理配置中定义)

# Usage notes (使用说明)
usage: |
  1. 定义工作流节点和边（指定代理和执行流）
  2. 选择合适的模式（react, reflection 等）
  3. 配置检查点以支持人工干预
  4. 通过框架加载并执行工作流
